version: '3'
services:
  certgen:
    image: debian
    build:
      context: .
      dockerfile: certgen/Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
    volumes:
      - dispatcher_certs:/dispatcher-agent-certs
      - configuration_certs:/configuration-agent-certs
      - mqtt_broker_certs:/mqtt-broker-certs
    command: /bin/bash /generate-certs.sh

  dispatcher:
    build:
      context: .
      dockerfile: dispatcher/Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
    environment:
      - MQTT_HOST=mosquitto
      - MQTT_PORT=8883
      - MQTT_CA_CERTS=/certs/mqtt-ca.crt
      - MQTT_CLIENT_CERTS=/certs/dispatcher-agent.crt
      - MQTT_CLIENT_KEYS=/certs/dispatcher-agent.key
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=${no_proxy}  
    volumes:
      - dispatcher_certs:/certs
    networks:
      - inbm_network
    depends_on:
      - certgen
  
  configuration:
    build:
      context: .
      dockerfile: configuration/Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
    environment:
      - MQTT_HOST=mosquitto
      - MQTT_PORT=8883
      - MQTT_CA_CERTS=/certs/mqtt-ca.crt
      - MQTT_CLIENT_CERTS=/certs/configuration-agent.crt
      - MQTT_CLIENT_KEYS=/certs/configuration-agent.key
    volumes:
      - configuration_certs:/certs
    networks:
      - inbm_network
    depends_on:
      - certgen

  mosquitto:
    build:
      context: .
      dockerfile: mosquitto/Dockerfile
    ports:
      - 8883:8883
    volumes:
      - mqtt_broker_certs:/certs
    networks:
      - inbm_network
    depends_on:
      - certgen
      
volumes:
  dispatcher_certs:
  configuration_certs:
  mqtt_broker_certs:

networks:
  inbm_network: